### ISSUE TITLE
How to get email when using api for retrieving and verifying tokens?

### ISSUE THREAD

**Issue by gitprats** [line/flutter_line_sdk#100]
## Is it a security issue?

No
## What did you do?

Cal Line api to get idtoken and verify it

## What did you expect?

firstname, lastname, email in the token

## What happened actually?

Token only contains name as below:

iss:https://access.line.me
sub:Ud1699a5d7fc9f2e0796189181d68c5a0
aud:2004784545
exp:1714720722
iat:1714717122
nonce:O_FLYKAQP6I3rfAG4UJtNfacdeCpc1Eu
amr:[] 1 item
name:Siya Sharma

## Sample project

> It would be appreciated if you can provide a link to or update a sample project that we can download and reproduce the issue.

**Comment by onevcat** [comment]
Hi,

To get the email information in the ID Token, you need to apply for it first. Please check the documentation here:

https://developers.line.biz/en/docs/line-login-sdks/ios-sdk/swift/managing-users/#apply-for-email-permission
