### ISSUE TITLE
Execution failed for task ':flutter_line_sdk:compileDebugKotlin'.

### ISSUE THREAD

**Issue by 2315594518** [line/flutter_line_sdk#110]
## Is it a security issue?
Launching lib\main.dart on sdk gphone64 x86 64 in debug mode...
Running Gradle task 'assembleDebug'...
����: [options] Դֵ 8 �ѹ�ʱ������δ�����а���ɾ��
����: [options] Ŀ��ֵ 8 �ѹ�ʱ������δ�����а���ɾ��
����: [options] Ҫ�����й��ѹ�ʱѡ��ľ���, ��ʹ�� -Xlint:-options��
3 ������
����: [options] Դֵ 8 �ѹ�ʱ������δ�����а���ɾ��
����: [options] Ŀ��ֵ 8 �ѹ�ʱ������δ�����а���ɾ��
����: [options] Ҫ�����й��ѹ�ʱѡ��ľ���, ��ʹ�� -Xlint:-options��
3 ������
����: [options] Դֵ 8 �ѹ�ʱ������δ�����а���ɾ��
����: [options] Ŀ��ֵ 8 �ѹ�ʱ������δ�����а���ɾ��
����: [options] Ҫ�����й��ѹ�ʱѡ��ľ���, ��ʹ�� -Xlint:-options��
3 ������
e: file:///C:/Users/wangzezhong/AppData/Local/Pub/Cache/hosted/pub.dev/flutter_line_sdk-2.3.8/android/src/main/kotlin/com/linecorp/flutter_line_sdk/util/CommonKotlinExension.kt:3:38 Unresolved reference 'BuildConfig'.
e: file:///C:/Users/wangzezhong/AppData/Local/Pub/Cache/hosted/pub.dev/flutter_line_sdk-2.3.8/android/src/main/kotlin/com/linecorp/flutter_line_sdk/util/CommonKotlinExension.kt:6:9 Unresolved reference 'BuildConfig'.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_line_sdk:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 13s
If you believe you have discovered a vulnerability or have an issue related to security, please **DO NOT** open a public issue. Instead, send us a mail to [dl_oss_dev@linecorp.com](mailto:dl_oss_dev@linecorp.com).

## What did you do?

> Please describe what you did before you encounter the issue.

android {
    namespace = "com.yoousi.comic"
    compileSdk = flutter.compileSdkVersion
//    ndkVersion = "26.1.10909125"

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_1_8
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId = "com.yoousi.comic"
        // You can update the following values to match your application needs.
        // For more information, see: https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration.
        minSdk = 24 // flutter.minSdkVersion is 21 while firebase_auth minSdkVersion is 23
        targetSdk = targetSdkVersion.toInteger()
        compileSdk = targetSdkVersion.toInteger()
        versionCode = flutterVersionCode.toInteger()
        versionName = flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig = signingConfigs.debug
        }
    }
}

plugins {
    id "dev.flutter.flutter-plugin-loader" version "1.0.0"
    id 'com.android.application' version '8.6.0' apply false
    id 'com.android.library' version '8.6.0' apply false
    id 'org.jetbrains.kotlin.android' version '2.0.20' apply false
    // START: FlutterFire Configuration
    id "com.google.gms.google-services" version "4.4.2" apply false
    // END: FlutterFire Configuration
}
## What did you expect?

> Please describe what you did expect to happen.

## What happened actually?

> Please describe what happened actually.

## Your environment?

> Some information of the environment in which the issue happened. Package version, Xcode version, iOS version, etc.
Android Studio Ladybug | 2024.2.1 Patch 1
 flutter doctor -v
[√] Flutter (Channel stable, 3.24.3, on Microsoft Windows [版本 10.0.22631.4317], locale zh-CN)
    • Flutter version 3.24.3 on channel stable at D:\dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (7 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at D:\android\sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = D:\android\sdk
    • Java binary at: D:\tools\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)
    • All Android licenses accepted
## Sample project

> It would be appreciated if you can provide a link to or update a sample project that we can download and reproduce the issue.

**Comment by onevcat** [comment]
@2315594518 
Can you check and follow #107 for now? We have a plan to upgrade the documentation and it is not yet done now.
