### ISSUE TITLE
Lost connection to device when hot restart in iOS.

### ISSUE THREAD

**Issue by hukusuke1007** [line/flutter_line_sdk#16]
## Is it a security issue?
none

## What did you do?

Lost connection to device when hot restart in iOS.
It occur in simulator and real device.

IDE: Android Studio.

## What did you expect?

Not lost connection to device.

## What happened actually?

Lost connection to device

## Your environment?

Android Studio: 3.5.3
iOS: 13.3

```
flutter doctor

[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.3 19D49f, locale ja-JP) 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Android Studio (version 3.5)
[!] IntelliJ IDEA Community Edition (version 2018.3.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.41.1)
[✓] Connected device (3 available)

! Doctor found issues in 1 category.
```

```
flutter --version

Flutter 1.12.13+hotfix.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 27321ebbad (3 weeks ago) • 2019-12-10 18:15:01 -0800
Engine • revision 2994f7e1e6
Tools • Dart 2.7.0
```

## Sample project

flutter_line_sdk example code

**Comment by onevcat** [comment]
This should be fixed in #17 and I will schedule a patch for it soon. However, please note that the channel ID or universal link setting will be not actually changed in a hot restart due to some native limitation on iOS. To change the channel ID (which should be a very rare demand), you still need to do a full build and restart.
