### ISSUE TITLE
Sending the result twice causes an error

### ISSUE THREAD

**Issue by najeira** [line/flutter_line_sdk#18]
## What did you do?

Not reproducible, but seems to send error twice under some conditions.
In rare cases, errors are measured in our app crash records.

## What did you expect?

https://github.com/line/flutter_line_sdk/blob/master/android/src/main/kotlin/com/linecorp/flutter_line_sdk/LineSdkWrapper.kt#L119

Here, since the method has not returned, the error will be sent again after this. `loginResult  = null` and `return true` seem necessary after the line.

**Comment by onevcat** [comment]
Should be fixed in #20
