### ISSUE TITLE
Can't run example code

### ISSUE THREAD

**Issue by raindy29** [line/flutter_line_sdk#2]
I use the example but can't execute it

`E/AndroidRuntime(22094): FATAL EXCEPTION: DefaultDispatcher-worker-1
E/AndroidRuntime(22094): Process: app.test.com, PID: 22094
E/AndroidRuntime(22094): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: DefaultDispatcher-worker-1
E/AndroidRuntime(22094): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:794)
E/AndroidRuntime(22094): 	at io.flutter.embedding.engine.FlutterJNI.invokePlatformMessageResponseCallback(FlutterJNI.java:727)
E/AndroidRuntime(22094): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:140)
E/AndroidRuntime(22094): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:230)
E/AndroidRuntime(22094): 	at com.linecorp.flutter_line_sdk.LineSdkWrapper$getCurrentAccessToken$1.invokeSuspend(LineSdkWrapper.kt:184)
E/AndroidRuntime(22094): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
E/AndroidRuntime(22094): 	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:236)
E/AndroidRuntime(22094): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
E/AndroidRuntime(22094): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
E/AndroidRuntime(22094): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
V/LifecycleChannel(22094): Sending AppLifecycleState.inactive message.
V/DartMessenger(22094): Sending message with callback over channel 'flutter/lifecycle'
V/DartMessenger(22094): Received message from Dart over channel 'flutter/platform'
V/DartMessenger(22094): Deferring to registered handler to process message.
V/PlatformChannel(22094): Received 'SystemChrome.setSystemUIOverlayStyle' message.
V/LifecycleChannel(22094): Sending AppLifecycleState.paused message.
V/DartMessenger(22094): Sending message with callback over channel 'flutter/lifecycle'
V/DartExecutor(22094): Detached from JNI. De-registering the platform message handler for this Dart execution context.
`

[√] Flutter (Channel beta, v1.7.8+hotfix.2, on Microsoft Windows [Version 6.1.7601], locale zh-TW)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.4)
[√] Connected device (2 available)

**Comment by onevcat** [comment]
@plateaukao Any idea?

**Comment by plateaukao** [comment]
Hi, @raindy29 
Thanks for reporting this issue. 
We had a fix for this. It should be fixed when pull request https://github.com/line/flutter_line_sdk/pull/3 is merged.

**Comment by onevcat** [comment]
@raindy29 
Version 1.0.2 should be released for this issue. Please try to upgrade and any feedback is welcome!
