### ISSUE TITLE
null safety?

### ISSUE THREAD

**Issue by tagby-haedongJeon** [line/flutter_line_sdk#37]
Will you support flutter 2.0, null-safety?

**Comment by onevcat** [comment]
@tagby-haedongJeon 
We are checking what we can do for it. Stay tuned!

**Comment by MacrotechJP** [comment]
@onevcat Thank you for your effort. We are looking forward to it.

**Comment by onevcat** [comment]
Version 2.0.0 is released and now it is null safety. :)

![截屏2021-04-05 11 11 12](https://user-images.githubusercontent.com/1019875/113529890-aa391980-95ff-11eb-9025-172ff58e9e10.png)
