### ISSUE TITLE
Android loginRequestCode is always zero

### ISSUE THREAD

**Issue by najeira** [line/flutter_line_sdk#4]
On Android, the Intent requestCode that launches the LINE app seems to always be zero.

## What did you expect?

Provide a way to set the requestCode or make the default requestCode random.

**Comment by onevcat** [comment]
@plateaukao Any idea on this?

**Comment by najeira** [comment]
For example, Facebook SDK uses `0xface`.

https://github.com/facebook/facebook-android-sdk/blob/master/facebook-core/src/main/java/com/facebook/FacebookSdk.java#L74

**Comment by plateaukao** [comment]
Hi, @najeira 

This issue is fixed with pull request #8 in master branch.
The released date will be decided later.

**Comment by onevcat** [comment]
Version 1.2.0 was released for this.
