### ISSUE TITLE
redirect_uri無法設定

### ISSUE THREAD

**Issue by a6a18** [line/flutter_line_sdk#42]
今天當我使用Line登入的時候，我發現如果手機沒有安裝Line App，程式就會自動導網頁登入，但是網頁登入若將LINE Login settings中的Web App開關打開，填入Redirect_uri使用。SDK中並沒有Option設定可填入Redirect_uri。

這樣的話是否只能將Web App的選項關閉？還是說有什麼方法可以在SDK中填入Redirect_uri ？

<img width="1136" alt="截圖 2021-04-24 上午1 53 09" src="https://user-images.githubusercontent.com/39345520/115910791-d974d500-a49f-11eb-875a-163c4e70892b.png">

**Comment by onevcat** [comment]
Even without LINE app installed and logging in with web page, as long as the login is performed from LINE SDK (and its components, such as the flutter version in this repo or the [Unity version](https://github.com/line/line-sdk-unity)), it uses setting from the "Mobile app" section. The callback URL is determined by your bundle ID with a fixed format so the setting in "Web app" will not be used.

**Comment by a6a18** [comment]
Normally, I think so too. But after testing the switch, it was found that it was indeed affected by the setting. it show me " redirect_uri does not match "

But after testing today, it is normal now....
