### ISSUE TITLE
which library intend to be used for liff

### ISSUE THREAD

**Issue by roticagas** [line/flutter_line_sdk#43]
Since flutter 2 officially add web ability from beta.
Which library should to be used with flutter web?

https://github.com/line/line-liff-v2-starter
or 
https://github.com/line/flutter_line_sdk

**Comment by onevcat** [comment]
This repo (`flutter_line_sdk`) is only providing a wrapper for the native LINE SDK. So it won't work with the Flutter Web.

LIFF is a front-end framework and LINE SDK (which is for [LINE Login](https://developers.line.biz/zh-hant/docs/line-login/) in native apps) is basically a different scope. So if you are going to create a LIFF app, I guess the LIFF repo is where you might want to go.

Best regards.
