### ISSUE TITLE
I can't get the Access Token.When i give correct channel id and package name give it

### ISSUE THREAD

**Issue by TAMILSELVAN943** [line/flutter_line_sdk#45]
## Is it a security issue?

If you believe you have discovered a vulnerability or have an issue related to security, please **DO NOT** open a public issue. Instead, send us a mail to [dl_oss_dev@linecorp.com](mailto:dl_oss_dev@linecorp.com).

## What did you do?

> Please describe what you did before you encounter the issue.

## What did you expect?

> Please describe what you did expect to happen.

## What happened actually?

> Please describe what happened actually.

## Your environment?

> Some information of the environment in which the issue happened. Package version, Xcode version, iOS version, etc.

## Sample project

> It would be appreciated if you can provide a link to or update a sample project that we can download and reproduce the issue.

**Comment by onevcat** [comment]
Hi,

The current information provided are not enough for us to see what can be wrong.

I suggest you try to print out the returned error if there is any. Usually there would contain more information about the login process if something goes wrong.

**Comment by TAMILSELVAN943** [comment]
It's my side problem.it's working fine

**Comment by plateaukao** [comment]
Close this issue because developer found what went wrong and it's working fine now..
