### ISSUE TITLE
How to get email when i line login

### ISSUE THREAD

**Issue by TAMILSELVAN943** [line/flutter_line_sdk#46]
## Is it a security issue?

If you believe you have discovered a vulnerability or have an issue related to security, please **DO NOT** open a public issue. Instead, send us a mail to [dl_oss_dev@linecorp.com](mailto:dl_oss_dev@linecorp.com).

## What did you do?

> Please describe what you did before you encounter the issue.

## What did you expect?

> Please describe what you did expect to happen.

## What happened actually?

> Please describe what happened actually.

## Your environment?

> Some information of the environment in which the issue happened. Package version, Xcode version, iOS version, etc.

## Sample project

> It would be appreciated if you can provide a link to or update a sample project that we can download and reproduce the issue.

**Comment by Selecao** [comment]
If using this SDK we can get lineUserId:
```
final loginResult = await LineSDK.instance.login(scopes: ["profile", "openid", "email"]);
final lineUserId = loginResult.userProfile?.userId;
```
How we can get lineEmail?

**Comment by onevcat** [comment]
The Email is contained in the `idToken` in the "email" field, if the user set it in LINE. You can use this code to get it:

```dart
final result = await LineSDK.instance.login(scopes: ["profile", "openid", "email"]);
final idToken = result.accessToken.idToken;
final userEmail = (idToken != null) ? idToken['email'] : null;
```

Please be careful since the user can choose to not share his/her email with you, or he/she might even not yet set an email address bound to the LINE account, this value could be `null` and you have to consider a way to handle it.

It is now a bit hard to use and not obvious. We will soon add a getter for the email address and release a new version for it.

**Comment by onevcat** [comment]
Per #58, once it gets merged, you can use the `email` to get it:

```dart
final result = await LineSDK.instance.login(scopes: ["profile", "openid", "email"]);
final userEmail = result.accessToken.email;
```

**Comment by Selecao** [comment]
> Per #58, once it gets merged, you can use the `email` to get it:
> 
> ```dart
> final result = await LineSDK.instance.login(scopes: ["profile", "openid", "email"]);
> final userEmail = result.accessToken.email;
> ```

@onevcat  there is no field .email after merging (already merged right?) but `result.accessToken.idToken?['email'] `has what i need, thank you!

**Comment by onevcat** [comment]
Sorry for the confusion, it is not tagged/released yet. I meant you can use it from the next version of `flutter_line_sdk`. I will prepare a tag for it today but it should be totally fine to just use your current way. They are the same.

**Comment by onevcat** [comment]
Version 2.2.0 was just released with this change. Find more in the [pub.dev](https://pub.dev/packages/flutter_line_sdk) or [repo release page](https://github.com/line/flutter_line_sdk/releases/tag/2.2.0).
