### ISSUE TITLE
how to get line email?

### ISSUE THREAD

**Issue by Selecao** [line/flutter_line_sdk#57]
If using this SDK we can get lineUserId:
```
final loginResult = await LineSDK.instance.login(scopes: ["profile", "openid", "email"]);
final lineUserId = loginResult.userProfile?.userId;
```
How we can get lineEmail?

_Originally posted by @Selecao in https://github.com/line/flutter_line_sdk/issues/46#issuecomment-1109795855_

**Comment by Selecao** [comment]
![Screenshot_2022-04-29-14-16-02-050_com android chrome](https://user-images.githubusercontent.com/10047476/165935163-8b7236d6-1995-400f-910f-9d9c0467d8f9.jpg)

> but when i logged there was a field with "profile", "openid", "email"

**Comment by onevcat** [comment]
Please see the comment in https://github.com/line/flutter_line_sdk/issues/46#issuecomment-1120541491
