### ISSUE TITLE
Flutter3.0

### ISSUE THREAD

**Issue by TaikiAsa** [line/flutter_line_sdk#59]
## What did you do?

Now,  I'm using version Flutter 3.0.
But, this SDK using Dart SDK version 2.16.2

## What did you expect?

Please version up.

## What happened actually?

```
flutter pub add flutter_line_sdk
The current Dart SDK version is 2.16.2.

Because PACKAGE_NAME requires SDK version >=2.17.0 <3.0.0, version solving failed.
```

**Comment by onevcat** [comment]
That is not a thing of Flutter version, but a requirement of Dart SDK version.

LINE SDK flutter requires from Dart SDK 2.12.0 (see [here]([flutter_line_sdk](https://github.com/line/flutter_line_sdk))) and your current version 2.16.2 is totally legal for this.

The reported issue

> Because PACKAGE_NAME requires SDK version >=2.17.0 <3.0.0, version solving failed.

indicates the `PACKAGE_NAME` requires Dart SDK 2.17.0, which I guess is not a requirement from this package. I would suggest you check to see how can you solve it by contacting the maintainer of `PACKAGE_NAME`.

**Comment by onevcat** [comment]
There is no additional information and since this package can work seamlessly with Flutter 3.0, I am closing this issue for now.

Feel free to reopen the discussion if there is any new information appended. Thanks!
