### ISSUE TITLE
flutter_line_sdk iOS 10.0 or later as the deployment target

### ISSUE THREAD

**Issue by JW-chenjingwei** [line/flutter_line_sdk#65]
## Is it a security issue?

no

## What did you do?
flutter_line_sdk ^2.3.0
> Please describe what you did before you encounter the issue.
this flutter_line_sdk as the deployment target iOS 10.0 or later, but dependency 'LineSDKSwift', '~> 5.3',In fact, LineSDKSwift dependency 5.9, this deployment target is iOS 11.0, So it will report an error.
## What did you expect?
Unified `flutter_line_sdk^2.3.0 `and `LineSDKSwift^5.9.0` deployment target
> Please describe what you did expect to happen.

## What happened actually?

> Please describe what happened actually.

## Your environment?
Xcode 14.0.1
mini deployment iOS12
> Some information of the environment in which the issue happened. Package version, Xcode version, iOS version, etc.

## Sample project

> It would be appreciated if you can provide a link to or update a sample project that we can download and reproduce the issue.

**Comment by onevcat** [comment]
Thanks for reporting!
This is a missed update to the podspec. I will see what I can do.

**Comment by JW-chenjingwei** [comment]
你好，来信已收到，谢谢

**Comment by onevcat** [comment]
2.3.1 was published for this issue. Now the package starts support from iOS 11.0.
