### ISSUE TITLE
Could not resolve all dependencies for configuration 

### ISSUE THREAD

**Issue by prohunterallen** [line/flutter_line_sdk#68]
On Android Studio Grandle Sync 

Gradle sync failed: Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'.
Could not determine artifacts for com.linecorp.linesdk:linesdk:5.4.1: 

On flutter build
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':flutter_line_sdk' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50

Setting
Flutter version 3.3.4
kotlin_version = '1.7.20'
com.android.tools.build:gradle:7.3.1

**Comment by onevcat** [comment]
@plateaukao Should we try to make a looser requirement to allow resolving in different plugin versions? (Is it possible?) Or do you have any idea about how can we solve this? Thanks!

**Comment by prohunterallen** [comment]
I have changed kotlin to 1.7.10 and downgrade gradle to 7.1.3 
then error has gone

suggestion update linesdk (com.linecorp.linesdk:linesdk) to higher 
https://mvnrepository.com/artifact/com.linecorp.linesdk/linesdk/5.8.0
