### ISSUE TITLE
[iOS] Signing for "LineSDKSwift-LineSDK" requires a development team

### ISSUE THREAD

**Issue by blaizechuang** [line/flutter_line_sdk#69]
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.6.1 21G217 darwin-x64, locale
    zh-Hant-TW)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

The plugin I used is 2.3.1 and after upgrading Xcode to 14.1, I got this error and build failed with below message.

_Signing for "LineSDKSwift-LineSDK" requires a development team. Select a development team in the Signing & Capabilities editor._

**Comment by blaizechuang** [comment]
https://stackoverflow.com/questions/72561696/xcode-14-needs-selected-development-team-for-pod-bundles

This solution can workaround this issue

**Comment by onevcat** [comment]
It is promised to be fixed in CocoaPods 1.12.0 ([Ref](https://github.com/CocoaPods/CocoaPods/issues/11402#issuecomment-1379702414)) so I guess we would choose to just close this one, since it is not a `flutter_line_sdk` issue after all.
