### ISSUE TITLE
Cannot resolve Android's dependency

### ISSUE THREAD

**Issue by geckour** [line/flutter_line_sdk#78]
## Is it a security issue?

No

## What did you do?

Build Flutter app which depends on this package

## What did you expect?

Successfully complete the build

## What happened actually?

Failed to build the app due to `flutter_line_sdk` depends on `line-sdk-android:5.4.1` but the version of the library does not exist on Maven Central or other repositories

## Your environment?

Package version: 2.3.2

## Sample project

N/A

**Comment by kouhon** [comment]
i have same problem.

**Comment by onevcat** [comment]
@plateaukao Can you check this?

**Comment by onevcat** [comment]
Fixed in #80 and I will tag the latest change with several others very soon!

**Comment by onevcat** [comment]
[2.3.3](https://github.com/line/flutter_line_sdk/releases/tag/2.3.3) was released and contained the fixes.

Please do a flutter upgrade and the build should work fine now. Sorry for the inconvenience it caused and thank you all for reporting this.

Happy Code & Good Luck!
