### ISSUE TITLE
Android Studio emulator  can't open the login page

### ISSUE THREAD

**Issue by kiesoman** [line/flutter_line_sdk#83]
I download the example code and try to run on the Android studio.
When i click the  signin  button, the page direct to the login page address, but stop and nothing show.
Then i try to test on the phone, everything is o.k..
I don't know what's  wrong, Could I get any advice?
Thanks first.

**Comment by onevcat** [comment]
It is more likely a simulator or host network issue. I guess there would be very little we can do in the SDK side.

Is it reproducible after a few time or on another environment?

**Comment by onevcat** [comment]
Hi，

I guess we found a front-end regression recently, which might be related to the issue.

On some old system (either iOS and Android), the JavaScript engine shipped in the system browser (WebKit) might fail to execute some code. It is tracked in [this issue](https://github.com/line/line-sdk-ios-swift/issues/189) and hopefully a patch will be applied to the login page soon.

**Comment by kiesoman** [comment]
HIHI,
I found the point, 
I try to manually open emulator with my target DNS. The problem disappear.
I don't know the better solution. for your reference.

Have a nice day.

**Comment by onevcat** [comment]
Oh,

That sounds reasonable! Thanks for the feedback.
