### ISSUE TITLE
[Feature] get phone number from app login

### ISSUE THREAD

**Issue by chutchatut** [line/flutter_line_sdk#92]
## Is it a security issue?

> No

## What did you do?

> Login using flutter line SDK.

## What did you expect?

> I should be able to specific 'phone' in scopes and get phone number as a result.

**Comment by onevcat** [comment]
Hi,

The phone number of the user is not a valid public scope for LINE SDK or LINE Login users. Please check the related documentation to know available permission scopes: https://developers.line.biz/en/docs/line-login/integrate-line-login/#scopes

**Comment by onevcat** [comment]
Since there is no further response, I am closing this for now. Please contact to the sales team for further support if you need this.
