### ISSUE TITLE
Want minSdkVersion to revert to 21

### ISSUE THREAD

**Issue by hello-coder-xu** [line/flutter_line_sdk#95]
## Is it a security issue?

No

## What did you do?

> Our project minSdk=21, I upgraded flutter_line_sdk: 2.3.6, the compilation failed

## What did you expect?

> Restore minSdk=21

**Comment by onevcat** [comment]
Thank you for reaching out to us. 

We truly appreciate your understanding and the needs you've expressed. However, the LINE SDK project, including both LINE SDK for Android and the `flutter_line_sdk` wrapper in this repository, follows its own development pace and schedule. Considering the variety of system versions used by LINE app users, aiming for the highest possible stability and quality of service, it may be challenging for us to revert changes and continue supporting API Level 21. We hope for your understanding in this matter. 

It's worth noting that the updates within the LINE SDK are not immediately necessary; you may choose to upgrade when your project is ready to update to support for newer Android versions. 

Thank you again for the understanding!
