### ISSUE TITLE
Cancel / OK Button Event

### ISSUE THREAD

**Issue by PANGSHENGFENG69** [line/flutter_line_sdk#96]
(PHYSICAL PHONE) - Iphone 11
I am facing PlatformException(3003, User cancelled or interrupted the login process., [:], null) after tapped "OK" Button,Why? 
And it shouldnt be same event when tapped "Cancel" Button.

(Iphone 11 Simulator)
When tapped Both button ("OK" / "Cancel") , It will not have any event, just stuck

Please help me !

![messageImage_1709706889647](https://github.com/line/flutter_line_sdk/assets/80751783/6afd37c6-1aec-471f-af93-03872b647804)
![messageImage_1709706896426](https://github.com/line/flutter_line_sdk/assets/80751783/d6487bc5-06dc-4b59-82b5-c8b67b72414c)

**Comment by onevcat** [comment]
Hi,

Usually it is because the open URL event is not correctly handled.

Do you know whether you are using the legacy "single window based app" or the new "window scene based app"?

Or, may I know the Flutter version you are using?

**Comment by PANGSHENGFENG69** [comment]
> Hi,
> 
> Usually it is because the open URL event is not correctly handled.
> 
> Do you know whether you are using the legacy "single window based app" or the new "window scene based app"?
> 
> Or, may I know the Flutter version you are using?

**Comment by PANGSHENGFENG69** [comment]
> Hi,
> 
> Usually it is because the open URL event is not correctly handled.
> 
> Do you know whether you are using the legacy "single window based app" or the new "window scene based app"?
> 
> Or, may I know the Flutter version you are using?

Also, did you mean the "line3rdp${MY BUNDLE ID}" is incorrected?
